version: '3'

services:
  jenkins:
    image: jenkins/jenkins:latest
    #image: custom-jenkins-node:latest
    # build: .
    container_name: jenkins-container
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
    environment:
      - JENKINS_JAVA_OPTIONS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
